import numpy as np

LIBRISPEECH_SAMPLE_RATE = 44100
LIBRISPEECH_COMPONENTS = 2048
LIBRISPEECH_HOP_LENGTH = 256
EPSILON = 1e-8
STFT_CROP_WIDTH = 64

SPEAKER_DATA_PATH = "data/processed/LibriSpeech/SPEAKERS.TXT"

NUMBER_OF_CLASSES = 2  # female, male

MAGNITUDE_NONLINEARITY = 1 / 8
